apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
  labels:
    app: go-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-microservice
  template:
    metadata:
      labels:
        app: go-microservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "go-microservice"
        dapr.io/port: "6000"
    spec:
      containers:
      - name: go-microservice
        image: <YOUR_CONTAINER_REGISTRY/YOUR_CONTAINER_IMAGE>
        ports:
        - containerPort: 6000
        imagePullPolicy: Always
