# See https://github.com/dapr/docs/blob/master/concepts/bindings/specs/http.md for example
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <name>
spec:
  type: bindings.http
  metadata:
  - name: url
    value: http://something.com
  - name: method
    value: GET