# See https://docs.dapr.io/operations/components/setup-bindings/supported-bindings/http/ for example
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <name>
spec:
  type: bindings.http
  metadata:
  - name: url
    value: http://something.com
  - name: method
    value: GET